# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\GitHub\Nominatim-Qgis-Plugin\nominatim\dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName("search")
        search.resize(296, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(search.sizePolicy().hasHeightForWidth())
        search.setSizePolicy(sizePolicy)
        search.setMinimumSize(QtCore.QSize(266, 345))
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(8, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.editSearch = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSearch.sizePolicy().hasHeightForWidth())
        self.editSearch.setSizePolicy(sizePolicy)
        self.editSearch.setMinimumSize(QtCore.QSize(20, 0))
        self.editSearch.setWhatsThis("")
        self.editSearch.setText("")
        self.editSearch.setObjectName("editSearch")
        self.horizontalLayout_4.addWidget(self.editSearch)
        self.btnSearch = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_4.addWidget(self.btnSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbExtent = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.cbExtent.setObjectName("cbExtent")
        self.horizontalLayout.addWidget(self.cbExtent)
        self.btnLocalize = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnLocalize.setObjectName("btnLocalize")
        self.horizontalLayout.addWidget(self.btnLocalize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableResult = QtWidgets.QTableWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableResult.sizePolicy().hasHeightForWidth())
        self.tableResult.setSizePolicy(sizePolicy)
        self.tableResult.setMinimumSize(QtCore.QSize(0, 30))
        self.tableResult.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableResult.setFont(font)
        self.tableResult.setMouseTracking(True)
        self.tableResult.setAlternatingRowColors(True)
        self.tableResult.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableResult.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableResult.setShowGrid(False)
        self.tableResult.setGridStyle(QtCore.Qt.SolidLine)
        self.tableResult.setRowCount(0)
        self.tableResult.setColumnCount(3)
        self.tableResult.setObjectName("tableResult")
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        self.tableResult.horizontalHeader().setVisible(True)
        self.tableResult.horizontalHeader().setSortIndicatorShown(True)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.verticalHeader().setDefaultSectionSize(17)
        self.tableResult.verticalHeader().setMinimumSectionSize(18)
        self.tableResult.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableResult)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnHelp = QtWidgets.QToolButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Documents and Settings/culos/.qgis/python/plugins/atlas/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout_2.addWidget(self.btnHelp)
        self.btnLayer = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnLayer.setObjectName("btnLayer")
        self.horizontalLayout_2.addWidget(self.btnLayer)
        self.btnMask = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnMask.setObjectName("btnMask")
        self.horizontalLayout_2.addWidget(self.btnMask)
        self.btnApply = QtWidgets.QToolButton(self.dockWidgetContents)
        self.btnApply.setMinimumSize(QtCore.QSize(0, 0))
        self.btnApply.setMouseTracking(False)
        self.btnApply.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnApply.setAcceptDrops(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow_green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApply.setIcon(icon1)
        self.btnApply.setCheckable(False)
        self.btnApply.setAutoExclusive(False)
        self.btnApply.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnApply.setAutoRaise(False)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout_2.addWidget(self.btnApply)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        search.setWidget(self.dockWidgetContents)
        self.label.setBuddy(self.editSearch)

        self.retranslateUi(search)
        QtCore.QMetaObject.connectSlotsByName(search)
        search.setTabOrder(self.editSearch, self.btnSearch)
        search.setTabOrder(self.btnSearch, self.cbExtent)
        search.setTabOrder(self.cbExtent, self.btnLocalize)
        search.setTabOrder(self.btnLocalize, self.tableResult)
        search.setTabOrder(self.tableResult, self.btnHelp)
        search.setTabOrder(self.btnHelp, self.btnLayer)
        search.setTabOrder(self.btnLayer, self.btnMask)
        search.setTabOrder(self.btnMask, self.btnApply)

    def retranslateUi(self, search):
        _translate = QtCore.QCoreApplication.translate
        search.setWindowTitle(_translate("search", "OSM place search..."))
        self.label.setText(_translate("search", "Name contains..."))
        self.btnSearch.setText(_translate("search", "->"))
        self.cbExtent.setText(_translate("search", "Limit to extent"))
        self.btnLocalize.setToolTip(_translate("search", "Where am I ?"))
        self.btnLocalize.setText(_translate("search", "<-"))
        self.tableResult.setToolTip(_translate("search", "Double-click to zoom"))
        self.tableResult.setStatusTip(_translate("search", "Results"))
        self.tableResult.setSortingEnabled(True)
        item = self.tableResult.horizontalHeaderItem(0)
        item.setText(_translate("search", "Name"))
        item = self.tableResult.horizontalHeaderItem(1)
        item.setText(_translate("search", "Class"))
        item = self.tableResult.horizontalHeaderItem(2)
        item.setText(_translate("search", "Infos"))
        self.btnHelp.setText(_translate("search", "..."))
        self.btnLayer.setToolTip(_translate("search", "add object in new layer"))
        self.btnLayer.setText(_translate("search", "Layer"))
        self.btnMask.setToolTip(_translate("search", "create mask from selected object"))
        self.btnMask.setText(_translate("search", "Mask"))
        self.btnApply.setText(_translate("search", "Zoom"))

