# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\projets\QGis plugins\geonames_search\ui_geonames_search_dlg.ui'
#
# Created: Tue Apr  9 15:32:39 2013
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

_fromUtf8 = lambda s: (s.decode("utf-8").encode("latin-1")) if s else s
_toUtf8 = lambda s: s.decode("latin-1").encode("utf-8") if s else s


class Ui_geonames_search_dlg(object):
    def setupUi(self, geonames_search_dlg):
        geonames_search_dlg.setObjectName(_fromUtf8("geonames_search_dlg"))
        geonames_search_dlg.setWindowModality(QtCore.Qt.NonModal)
        geonames_search_dlg.setEnabled(True)
        geonames_search_dlg.resize(584, 463)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(geonames_search_dlg.sizePolicy().hasHeightForWidth())
        geonames_search_dlg.setSizePolicy(sizePolicy)
        geonames_search_dlg.setSizeGripEnabled(True)
        geonames_search_dlg.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(geonames_search_dlg)
        self.verticalLayout.setContentsMargins(8, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(geonames_search_dlg)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(geonames_search_dlg)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.btnHelp = QtGui.QToolButton(geonames_search_dlg)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Documents and Settings/culos/.qgis/python/plugins/atlas/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.horizontalLayout_3.addWidget(self.btnHelp)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cbA = QtGui.QCheckBox(geonames_search_dlg)
        self.cbA.setObjectName(_fromUtf8("cbA"))
        self.verticalLayout_4.addWidget(self.cbA)
        self.cbH = QtGui.QCheckBox(geonames_search_dlg)
        self.cbH.setObjectName(_fromUtf8("cbH"))
        self.verticalLayout_4.addWidget(self.cbH)
        self.cbL = QtGui.QCheckBox(geonames_search_dlg)
        self.cbL.setObjectName(_fromUtf8("cbL"))
        self.verticalLayout_4.addWidget(self.cbL)
        self.cbP = QtGui.QCheckBox(geonames_search_dlg)
        self.cbP.setObjectName(_fromUtf8("cbP"))
        self.verticalLayout_4.addWidget(self.cbP)
        self.cbR = QtGui.QCheckBox(geonames_search_dlg)
        self.cbR.setObjectName(_fromUtf8("cbR"))
        self.verticalLayout_4.addWidget(self.cbR)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cbS = QtGui.QCheckBox(geonames_search_dlg)
        self.cbS.setObjectName(_fromUtf8("cbS"))
        self.verticalLayout_3.addWidget(self.cbS)
        self.cbT = QtGui.QCheckBox(geonames_search_dlg)
        self.cbT.setObjectName(_fromUtf8("cbT"))
        self.verticalLayout_3.addWidget(self.cbT)
        self.cbV = QtGui.QCheckBox(geonames_search_dlg)
        self.cbV.setObjectName(_fromUtf8("cbV"))
        self.verticalLayout_3.addWidget(self.cbV)
        self.cbU = QtGui.QCheckBox(geonames_search_dlg)
        self.cbU.setObjectName(_fromUtf8("cbU"))
        self.verticalLayout_3.addWidget(self.cbU)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(geonames_search_dlg)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.editSearch = QtGui.QLineEdit(geonames_search_dlg)
        self.editSearch.setText(_fromUtf8(""))
        self.editSearch.setObjectName(_fromUtf8("editSearch"))
        self.horizontalLayout_4.addWidget(self.editSearch)
        self.cbExtent = QtGui.QCheckBox(geonames_search_dlg)
        self.cbExtent.setObjectName(_fromUtf8("cbExtent"))
        self.horizontalLayout_4.addWidget(self.cbExtent)
        self.btnSearch = QtGui.QToolButton(geonames_search_dlg)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.horizontalLayout_4.addWidget(self.btnSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableResult = QtGui.QTableWidget(geonames_search_dlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableResult.sizePolicy().hasHeightForWidth())
        self.tableResult.setSizePolicy(sizePolicy)
        self.tableResult.setMinimumSize(QtCore.QSize(370, 144))
        self.tableResult.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableResult.setFont(font)
        self.tableResult.setAlternatingRowColors(True)
        self.tableResult.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableResult.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableResult.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableResult.setShowGrid(False)
        self.tableResult.setGridStyle(QtCore.Qt.SolidLine)
        self.tableResult.setRowCount(0)
        self.tableResult.setColumnCount(3)
        self.tableResult.setObjectName(_fromUtf8("tableResult"))
        self.tableResult.setColumnCount(3)
        self.tableResult.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        self.tableResult.horizontalHeader().setVisible(True)
        self.tableResult.horizontalHeader().setSortIndicatorShown(True)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.verticalHeader().setDefaultSectionSize(17)
        self.tableResult.verticalHeader().setMinimumSectionSize(18)
        self.tableResult.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.tableResult)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.zoomPrec = QtGui.QToolButton(geonames_search_dlg)
        self.zoomPrec.setObjectName(_fromUtf8("zoomPrec"))
        self.horizontalLayout_2.addWidget(self.zoomPrec)
        self.btnApply = QtGui.QToolButton(geonames_search_dlg)
        self.btnApply.setMinimumSize(QtCore.QSize(0, 0))
        self.btnApply.setMouseTracking(False)
        self.btnApply.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnApply.setAcceptDrops(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("arrow_green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApply.setIcon(icon1)
        self.btnApply.setCheckable(False)
        self.btnApply.setAutoExclusive(False)
        self.btnApply.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnApply.setAutoRaise(False)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout_2.addWidget(self.btnApply)
        self.btnClose = QtGui.QToolButton(geonames_search_dlg)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label.setBuddy(self.editSearch)

        self.retranslateUi(geonames_search_dlg)
        QtCore.QMetaObject.connectSlotsByName(geonames_search_dlg)
        geonames_search_dlg.setTabOrder(self.cbA, self.cbH)
        geonames_search_dlg.setTabOrder(self.cbH, self.cbL)
        geonames_search_dlg.setTabOrder(self.cbL, self.cbP)
        geonames_search_dlg.setTabOrder(self.cbP, self.cbR)
        geonames_search_dlg.setTabOrder(self.cbR, self.cbS)
        geonames_search_dlg.setTabOrder(self.cbS, self.cbT)
        geonames_search_dlg.setTabOrder(self.cbT, self.cbV)
        geonames_search_dlg.setTabOrder(self.cbV, self.cbU)
        geonames_search_dlg.setTabOrder(self.cbU, self.editSearch)
        geonames_search_dlg.setTabOrder(self.editSearch, self.btnSearch)
        geonames_search_dlg.setTabOrder(self.btnSearch, self.tableResult)
        geonames_search_dlg.setTabOrder(self.tableResult, self.zoomPrec)
        geonames_search_dlg.setTabOrder(self.zoomPrec, self.btnApply)
        geonames_search_dlg.setTabOrder(self.btnApply, self.btnClose)

    def retranslateUi(self, geonames_search_dlg):
        geonames_search_dlg.setWindowTitle(QtGui.QApplication.translate("geonames_search_dlg", "Geonames search...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("geonames_search_dlg", "Limit search to...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("geonames_search_dlg", "<a href=\"http://www.geonames.org\">www.geonames.org</a>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHelp.setText(QtGui.QApplication.translate("geonames_search_dlg", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbA.setText(QtGui.QApplication.translate("geonames_search_dlg", "Country, state, region,...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbH.setText(QtGui.QApplication.translate("geonames_search_dlg", "Stream, lake, ...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbL.setText(QtGui.QApplication.translate("geonames_search_dlg", "Parks,area, ...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbP.setText(QtGui.QApplication.translate("geonames_search_dlg", "City, village,...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbR.setText(QtGui.QApplication.translate("geonames_search_dlg", "Road, railroad", None, QtGui.QApplication.UnicodeUTF8))
        self.cbS.setText(QtGui.QApplication.translate("geonames_search_dlg", "Spot, building, farm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbT.setText(QtGui.QApplication.translate("geonames_search_dlg", "Mountain,hill,rock,...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbV.setText(QtGui.QApplication.translate("geonames_search_dlg", "Forest,heath,...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbU.setText(QtGui.QApplication.translate("geonames_search_dlg", "Undersea", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("geonames_search_dlg", "Name contains...", None, QtGui.QApplication.UnicodeUTF8))
        self.editSearch.setWhatsThis(QtGui.QApplication.translate("geonames_search_dlg", "aa", None, QtGui.QApplication.UnicodeUTF8))
        self.cbExtent.setText(QtGui.QApplication.translate("geonames_search_dlg", "Limit to extent", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("geonames_search_dlg", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.tableResult.setToolTip(QtGui.QApplication.translate("geonames_search_dlg", "Double-click to zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.tableResult.setStatusTip(QtGui.QApplication.translate("geonames_search_dlg", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tableResult.setSortingEnabled(True)
        self.tableResult.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("geonames_search_dlg", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableResult.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("geonames_search_dlg", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.tableResult.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("geonames_search_dlg", "Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomPrec.setText(QtGui.QApplication.translate("geonames_search_dlg", "Initial view", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApply.setText(QtGui.QApplication.translate("geonames_search_dlg", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("geonames_search_dlg", "Close", None, QtGui.QApplication.UnicodeUTF8))

